use_frameworks!

platform :ios, '10.0'

target 'YSRemoteInspector_Example' do
  pod 'YSRemoteInspector', :path => '../'

  target 'YSRemoteInspector_Tests' do
    inherit! :search_paths

    
  end
end
